Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,7 +39,7 @@ jobs:
 
     - name: Verify server is running and log output
       run: |
-        curl -I http://localhost:8080 || { echo "Failed to connect to server"; exit 1; }
+        curl -I http://localhost:80 || { echo "Failed to connect to server"; exit 1; }
         echo "Server verification completed"
         echo "=== Server Log Output ==="
         cat /var/log/nginx/error.log || echo "No server log found"
@@ -49,14 +49,14 @@ jobs:
       run: |
         echo "Testing proxy with curl command..."
         for i in {1..6}; do
-          curl -sSf "http://localhost:8080/proxy/?api-key=7cd2ddae-9f2e-481c-99d0-404e7bc7a0b2&service=WCS&version=2.0.1&request=GetCoverage&CoverageID=korkeusmalli_2m&SUBSET=E%28354468,354472%29&SUBSET=N%286650556,6650560%29&format=text/plain" -H "Content-Type: application/json" && echo "Check $i/6 - Status OK" || { echo "Check $i/6 - Server is down"; break; }
+          curl -sSf "http://localhost:80/proxy/?api-key=7cd2ddae-9f2e-481c-99d0-404e7bc7a0b2&service=WCS&version=2.0.1&request=GetCoverage&CoverageID=korkeusmalli_2m&SUBSET=E%28354468,354472%29&SUBSET=N%286650556,6650560%29&format=text/plain" -H "Content-Type: application/json" && echo "Check $i/6 - Status OK" || { echo "Check $i/6 - Server is down"; break; }
           sleep 10
         done
 
     - name: Execute OPTIONS curl command to test CORS headers
       run: |
         echo "Testing CORS headers with OPTIONS curl command..."
-        curl -X OPTIONS -i "http://localhost:8080/proxy/?api-key=7cd2ddae-9f2e-481c-99d0-404e7bc7a0b2&service=WCS&version=2.0.1&request=GetCoverage&CoverageID=korkeusmalli_2m&SUBSET=E(354468,354472)&SUBSET=N(6650556,6650560)&format=text/plain"
+        curl -X OPTIONS -i "http://localhost:80/proxy/?api-key=7cd2ddae-9f2e-481c-99d0-404e7bc7a0b2&service=WCS&version=2.0.1&request=GetCoverage&CoverageID=korkeusmalli_2m&SUBSET=E(354468,354472)&SUBSET=N(6650556,6650560)&format=text/plain"
 
     - name: Execute direct curl command to test request
       run: |
